server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          surveymonkey:
            provider:                     "surveymonkey"
            client-name:                  "Surveymonkey"
            client-id:                    "[env]"
            client-secret:                "[env]"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "post"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
        provider: 
          surveymonkey:
            authorization-uri:   "https://api.surveymonkey.com/oauth/authorize"
            token-uri:           "https://api.surveymonkey.com/oauth/token"
            user-info-uri:       "https://api.surveymonkey.com/v3/users/me"
  profiles:
    active:
    - dev
    - ssl

logging:
  level:
    root: WARN
    com.example.spring.yconnect: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG